name: Render Architecture Diagram

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/architecture.dot'
      - 'render-diagram.sh'
      - '.github/workflows/diagram.yml'
  workflow_dispatch:

permissions:
  contents: write  # allow committing generated images

concurrency:
  group: diagram-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark workspace safe for git (avoids 'dubious ownership')
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Render diagram
        run: |
          set -euo pipefail
          if [ -x "./render-diagram.sh" ]; then
            ./render-diagram.sh
          else
            dot -Tpng docs/architecture.dot -o docs/architecture.png
            dot -Tsvg docs/architecture.dot -o docs/architecture.svg
          fi

      - name: Commit & push generated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): render architecture diagram"
          file_pattern: |
            docs/architecture.png
            docs/architecture.svg
